# Generated by Django 5.1.4 on 2025-06-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_alter_article_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
