services:
  app:
    container_name: django_app
    build:
      dockerfile: ./Dockerfile
    volumes: 
      - .:/mysite
      - ./mysite/database:/app/database  
      - ./static:/app/static
      - ./static/media:/app/static/media
    env_file: 
      - ./.env 
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    ports: 
      - 8000:8000
    restart: always
    logging:
      driver: loki
      options:
        # loki-url: http://host.docker.internal:3100/loki/api/v1/push
        loki-url: http://localhost:3100/loki/api/v1/push

  nginx:
    container_name: nginx
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./static:/app/static
      - ./static/media:/app/static/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    depends_on:
      - app

  grafana:
    container_name: django_grafana
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000

  loki:
    container_name: django_loki
    image: grafana/loki:latest
    ports:
      - 3100:3100
