# Generated by Django 5.1.4 on 2025-05-31 09:34

import myauth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=myauth.utils.profile_avatar_directory_path,
            ),
        ),
    ]
