# Generated by Django 5.1.4 on 2025-01-29 06:45

import django.core.validators
import shopapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.SmallIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=100, validators=[shopapp.validators.starting_with_letter]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
