# Generated by Django 5.1.4 on 2025-05-31 07:38

import shopapp.models
import shopapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0013_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=shopapp.models.product_images_directory_path
            ),
        ),
    ]
