# Generated by Django 5.1.4 on 2025-06-12 10:21

import shopapp.models
import shopapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0014_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=100,
                validators=[shopapp.validators.starting_with_letter],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_preview_directory_path,
                verbose_name="preview",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=shopapp.models.product_images_directory_path,
                verbose_name="image",
            ),
        ),
    ]
